"""Update model Payment and Suscription.

Revision ID: 0fcdf411a6db
Revises: 381e4b5c0e66
Create Date: 2025-10-14 16:56:38.956849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fcdf411a6db'
down_revision: Union[str, None] = '381e4b5c0e66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('payment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subscriptions', 'payments', ['payment_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'payment_id')
    # ### end Alembic commands ###
