"""Fix model Subsription(payment_id).

Revision ID: dfd8436a72df
Revises: 0fcdf411a6db
Create Date: 2025-10-14 17:30:42.317607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfd8436a72df'
down_revision: Union[str, None] = '0fcdf411a6db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subscriptions_payment_id_fkey', 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'payment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('subscriptions_payment_id_fkey', 'subscriptions', 'payments', ['payment_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
